
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.com.rcs.Stubs;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-05-20T14:27:26.509-03:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "CalcPrecoPrazoWS",
                      portName = "CalcPrecoPrazoWSSoap12",
                      targetNamespace = "http://tempuri.org/",
                      wsdlLocation = "http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL",
                      endpointInterface = "it.com.rcs.Stubs.CalcPrecoPrazoWSSoap")

public class CalcPrecoPrazoWSSoap12Impl implements CalcPrecoPrazoWSSoap {

    private static final Logger LOG = Logger.getLogger(CalcPrecoPrazoWSSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcPrazoRestricao(java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String sDtCalculo)*
     */
    public it.com.rcs.Stubs.CResultado calcPrazoRestricao(java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String sDtCalculo) {
        LOG.info("Executing operation calcPrazoRestricao");
        System.out.println(nCdServico);
        System.out.println(sCepOrigem);
        System.out.println(sCepDestino);
        System.out.println(sDtCalculo);
        try {
            it.com.rcs.Stubs.CResultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcPrecoFAC(java.lang.String nCdServico, java.lang.String nVlPeso, java.lang.String strDataCalculo)*
     */
    public it.com.rcs.Stubs.CResultado calcPrecoFAC(java.lang.String nCdServico, java.lang.String nVlPeso, java.lang.String strDataCalculo) {
        LOG.info("Executing operation calcPrecoFAC");
        System.out.println(nCdServico);
        System.out.println(nVlPeso);
        System.out.println(strDataCalculo);
        try {
            it.com.rcs.Stubs.CResultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcPreco(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento)*
     */
    public it.com.rcs.Stubs.CResultado calcPreco(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento) {
        LOG.info("Executing operation calcPreco");
        System.out.println(nCdEmpresa);
        System.out.println(sDsSenha);
        System.out.println(nCdServico);
        System.out.println(sCepOrigem);
        System.out.println(sCepDestino);
        System.out.println(nVlPeso);
        System.out.println(nCdFormato);
        System.out.println(nVlComprimento);
        System.out.println(nVlAltura);
        System.out.println(nVlLargura);
        System.out.println(nVlDiametro);
        System.out.println(sCdMaoPropria);
        System.out.println(nVlValorDeclarado);
        System.out.println(sCdAvisoRecebimento);
        try {
            it.com.rcs.Stubs.CResultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcPrazo(java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino)*
     */
    public it.com.rcs.Stubs.CResultado calcPrazo(java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino) {
        LOG.info("Executing operation calcPrazo");
        System.out.println(nCdServico);
        System.out.println(sCepOrigem);
        System.out.println(sCepDestino);
        try {
            it.com.rcs.Stubs.CResultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#verificaModal(java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino)*
     */
    public it.com.rcs.Stubs.CResultadoModal verificaModal(java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino) {
        LOG.info("Executing operation verificaModal");
        System.out.println(nCdServico);
        System.out.println(sCepOrigem);
        System.out.println(sCepDestino);
        try {
            it.com.rcs.Stubs.CResultadoModal _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#listaServicos()*
     */
    public it.com.rcs.Stubs.CResultadoServicos listaServicos() {
        LOG.info("Executing operation listaServicos");
        try {
            it.com.rcs.Stubs.CResultadoServicos _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#listaServicosSTAR()*
     */
    public it.com.rcs.Stubs.CResultadoServicos listaServicosSTAR() {
        LOG.info("Executing operation listaServicosSTAR");
        try {
            it.com.rcs.Stubs.CResultadoServicos _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcPrecoPrazo(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento)*
     */
    public it.com.rcs.Stubs.CResultado calcPrecoPrazo(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento) {
        LOG.info("Executing operation calcPrecoPrazo");
        System.out.println(nCdEmpresa);
        System.out.println(sDsSenha);
        System.out.println(nCdServico);
        System.out.println(sCepOrigem);
        System.out.println(sCepDestino);
        System.out.println(nVlPeso);
        System.out.println(nCdFormato);
        System.out.println(nVlComprimento);
        System.out.println(nVlAltura);
        System.out.println(nVlLargura);
        System.out.println(nVlDiametro);
        System.out.println(sCdMaoPropria);
        System.out.println(nVlValorDeclarado);
        System.out.println(sCdAvisoRecebimento);
        try {
            it.com.rcs.Stubs.CResultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcPrecoPrazoRestricao(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento, java.lang.String sDtCalculo)*
     */
    public it.com.rcs.Stubs.CResultado calcPrecoPrazoRestricao(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento, java.lang.String sDtCalculo) {
        LOG.info("Executing operation calcPrecoPrazoRestricao");
        System.out.println(nCdEmpresa);
        System.out.println(sDsSenha);
        System.out.println(nCdServico);
        System.out.println(sCepOrigem);
        System.out.println(sCepDestino);
        System.out.println(nVlPeso);
        System.out.println(nCdFormato);
        System.out.println(nVlComprimento);
        System.out.println(nVlAltura);
        System.out.println(nVlLargura);
        System.out.println(nVlDiametro);
        System.out.println(sCdMaoPropria);
        System.out.println(nVlValorDeclarado);
        System.out.println(sCdAvisoRecebimento);
        System.out.println(sDtCalculo);
        try {
            it.com.rcs.Stubs.CResultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcPrecoPrazoData(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento, java.lang.String sDtCalculo)*
     */
    public it.com.rcs.Stubs.CResultado calcPrecoPrazoData(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento, java.lang.String sDtCalculo) {
        LOG.info("Executing operation calcPrecoPrazoData");
        System.out.println(nCdEmpresa);
        System.out.println(sDsSenha);
        System.out.println(nCdServico);
        System.out.println(sCepOrigem);
        System.out.println(sCepDestino);
        System.out.println(nVlPeso);
        System.out.println(nCdFormato);
        System.out.println(nVlComprimento);
        System.out.println(nVlAltura);
        System.out.println(nVlLargura);
        System.out.println(nVlDiametro);
        System.out.println(sCdMaoPropria);
        System.out.println(nVlValorDeclarado);
        System.out.println(sCdAvisoRecebimento);
        System.out.println(sDtCalculo);
        try {
            it.com.rcs.Stubs.CResultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#getVersao()*
     */
    public it.com.rcs.Stubs.Versao getVersao() {
        LOG.info("Executing operation getVersao");
        try {
            it.com.rcs.Stubs.Versao _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcPrecoData(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento, java.lang.String sDtCalculo)*
     */
    public it.com.rcs.Stubs.CResultado calcPrecoData(java.lang.String nCdEmpresa, java.lang.String sDsSenha, java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String nVlPeso, int nCdFormato, java.math.BigDecimal nVlComprimento, java.math.BigDecimal nVlAltura, java.math.BigDecimal nVlLargura, java.math.BigDecimal nVlDiametro, java.lang.String sCdMaoPropria, java.math.BigDecimal nVlValorDeclarado, java.lang.String sCdAvisoRecebimento, java.lang.String sDtCalculo) {
        LOG.info("Executing operation calcPrecoData");
        System.out.println(nCdEmpresa);
        System.out.println(sDsSenha);
        System.out.println(nCdServico);
        System.out.println(sCepOrigem);
        System.out.println(sCepDestino);
        System.out.println(nVlPeso);
        System.out.println(nCdFormato);
        System.out.println(nVlComprimento);
        System.out.println(nVlAltura);
        System.out.println(nVlLargura);
        System.out.println(nVlDiametro);
        System.out.println(sCdMaoPropria);
        System.out.println(nVlValorDeclarado);
        System.out.println(sCdAvisoRecebimento);
        System.out.println(sDtCalculo);
        try {
            it.com.rcs.Stubs.CResultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcDataMaxima(java.lang.String codigoObjeto)*
     */
    public it.com.rcs.Stubs.CResultadoObjeto calcDataMaxima(java.lang.String codigoObjeto) {
        LOG.info("Executing operation calcDataMaxima");
        System.out.println(codigoObjeto);
        try {
            it.com.rcs.Stubs.CResultadoObjeto _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see it.com.rcs.Stubs.CalcPrecoPrazoWSSoap#calcPrazoData(java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String sDtCalculo)*
     */
    public it.com.rcs.Stubs.CResultado calcPrazoData(java.lang.String nCdServico, java.lang.String sCepOrigem, java.lang.String sCepDestino, java.lang.String sDtCalculo) {
        LOG.info("Executing operation calcPrazoData");
        System.out.println(nCdServico);
        System.out.println(sCepOrigem);
        System.out.println(sCepDestino);
        System.out.println(sDtCalculo);
        try {
            it.com.rcs.Stubs.CResultado _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
