package it.com.rcs.Stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-05-20T14:27:26.828-03:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "CalcPrecoPrazoWSHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CalcPrecoPrazoWSHttpGet {

    /**
     * Calcula o prazo considerando restrição de entrega
     */
    @WebMethod(operationName = "CalcPrazoRestricao")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrazoRestricao(
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    /**
     * Calcula os preços dos serviços FAC
     */
    @WebMethod(operationName = "CalcPrecoFAC")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoFAC(
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "strDataCalculo", name = "strDataCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String strDataCalculo
    );

    /**
     * Calcula somente o preço com a data atual
     */
    @WebMethod(operationName = "CalcPreco")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPreco(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento
    );

    /**
     * Calcula somente o prazo com a data atual
     */
    @WebMethod(operationName = "CalcPrazo")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrazo(
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino
    );

    /**
     * Método para mostrar se o trecho consultado utiliza modal aéreo ou terrestre
     */
    @WebMethod(operationName = "VerificaModal")
    @WebResult(name = "cResultadoModal", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultadoModal verificaModal(
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino
    );

    /**
     * Lista os serviços que estão disponíveis para cálculo de preço e/ou prazo
     */
    @WebMethod(operationName = "ListaServicos")
    @WebResult(name = "cResultadoServicos", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultadoServicos listaServicos();

    /**
     * Lista os serviços que são calculados pelo STAR
     */
    @WebMethod(operationName = "ListaServicosSTAR")
    @WebResult(name = "cResultadoServicos", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultadoServicos listaServicosSTAR();

    /**
     * Calcula o preço e o prazo com a data atual
     */
    @WebMethod(operationName = "CalcPrecoPrazo")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoPrazo(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento
    );

    /**
     * Calcula o preço e o prazo considerando as restrições de entrega
     */
    @WebMethod(operationName = "CalcPrecoPrazoRestricao")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoPrazoRestricao(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    /**
     * Calcula o preço e o prazo com uma data especificada
     */
    @WebMethod(operationName = "CalcPrecoPrazoData")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoPrazoData(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    /**
     * Retorna a versão atual do componente
     */
    @WebMethod
    @WebResult(name = "versao", targetNamespace = "http://tempuri.org/", partName = "Body")
    public Versao getVersao();

    /**
     * Calcula somente o preço com uma data especificada
     */
    @WebMethod(operationName = "CalcPrecoData")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrecoData(
        @WebParam(partName = "nCdEmpresa", name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdEmpresa,
        @WebParam(partName = "sDsSenha", name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        java.lang.String sDsSenha,
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "nVlPeso", name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlPeso,
        @WebParam(partName = "nCdFormato", name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdFormato,
        @WebParam(partName = "nVlComprimento", name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlComprimento,
        @WebParam(partName = "nVlAltura", name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlAltura,
        @WebParam(partName = "nVlLargura", name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlLargura,
        @WebParam(partName = "nVlDiametro", name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlDiametro,
        @WebParam(partName = "sCdMaoPropria", name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdMaoPropria,
        @WebParam(partName = "nVlValorDeclarado", name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        java.lang.String nVlValorDeclarado,
        @WebParam(partName = "sCdAvisoRecebimento", name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        java.lang.String sCdAvisoRecebimento,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );

    /**
     * Calcula a data máxima de entrega de determinado objeto
     */
    @WebMethod(operationName = "CalcDataMaxima")
    @WebResult(name = "cResultadoObjeto", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultadoObjeto calcDataMaxima(
        @WebParam(partName = "codigoObjeto", name = "codigoObjeto", targetNamespace = "http://tempuri.org/")
        java.lang.String codigoObjeto
    );

    /**
     * Calcula somente o prazo com uma data especificada
     */
    @WebMethod(operationName = "CalcPrazoData")
    @WebResult(name = "cResultado", targetNamespace = "http://tempuri.org/", partName = "Body")
    public CResultado calcPrazoData(
        @WebParam(partName = "nCdServico", name = "nCdServico", targetNamespace = "http://tempuri.org/")
        java.lang.String nCdServico,
        @WebParam(partName = "sCepOrigem", name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepOrigem,
        @WebParam(partName = "sCepDestino", name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        java.lang.String sCepDestino,
        @WebParam(partName = "sDtCalculo", name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        java.lang.String sDtCalculo
    );
}
