package it.com.rcs.Stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2019-05-20T14:27:26.886-03:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "CalcPrecoPrazoWS",
                  wsdlLocation = "http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL",
                  targetNamespace = "http://tempuri.org/")
public class CalcPrecoPrazoWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "CalcPrecoPrazoWS");
    public final static QName CalcPrecoPrazoWSSoap12 = new QName("http://tempuri.org/", "CalcPrecoPrazoWSSoap12");
    public final static QName CalcPrecoPrazoWSSoap = new QName("http://tempuri.org/", "CalcPrecoPrazoWSSoap");
    public final static QName CalcPrecoPrazoWSHttpGet = new QName("http://tempuri.org/", "CalcPrecoPrazoWSHttpGet");
    public final static QName CalcPrecoPrazoWSHttpPost = new QName("http://tempuri.org/", "CalcPrecoPrazoWSHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalcPrecoPrazoWS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public CalcPrecoPrazoWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalcPrecoPrazoWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcPrecoPrazoWS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalcPrecoPrazoWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalcPrecoPrazoWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalcPrecoPrazoWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CalcPrecoPrazoWSSoap
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSSoap12")
    public CalcPrecoPrazoWSSoap getCalcPrecoPrazoWSSoap12() {
        return super.getPort(CalcPrecoPrazoWSSoap12, CalcPrecoPrazoWSSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcPrecoPrazoWSSoap
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSSoap12")
    public CalcPrecoPrazoWSSoap getCalcPrecoPrazoWSSoap12(WebServiceFeature... features) {
        return super.getPort(CalcPrecoPrazoWSSoap12, CalcPrecoPrazoWSSoap.class, features);
    }


    /**
     *
     * @return
     *     returns CalcPrecoPrazoWSSoap
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSSoap")
    public CalcPrecoPrazoWSSoap getCalcPrecoPrazoWSSoap() {
        return super.getPort(CalcPrecoPrazoWSSoap, CalcPrecoPrazoWSSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcPrecoPrazoWSSoap
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSSoap")
    public CalcPrecoPrazoWSSoap getCalcPrecoPrazoWSSoap(WebServiceFeature... features) {
        return super.getPort(CalcPrecoPrazoWSSoap, CalcPrecoPrazoWSSoap.class, features);
    }


    /**
     *
     * @return
     *     returns CalcPrecoPrazoWSHttpGet
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSHttpGet")
    public CalcPrecoPrazoWSHttpGet getCalcPrecoPrazoWSHttpGet() {
        return super.getPort(CalcPrecoPrazoWSHttpGet, CalcPrecoPrazoWSHttpGet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcPrecoPrazoWSHttpGet
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSHttpGet")
    public CalcPrecoPrazoWSHttpGet getCalcPrecoPrazoWSHttpGet(WebServiceFeature... features) {
        return super.getPort(CalcPrecoPrazoWSHttpGet, CalcPrecoPrazoWSHttpGet.class, features);
    }


    /**
     *
     * @return
     *     returns CalcPrecoPrazoWSHttpPost
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSHttpPost")
    public CalcPrecoPrazoWSHttpPost getCalcPrecoPrazoWSHttpPost() {
        return super.getPort(CalcPrecoPrazoWSHttpPost, CalcPrecoPrazoWSHttpPost.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcPrecoPrazoWSHttpPost
     */
    @WebEndpoint(name = "CalcPrecoPrazoWSHttpPost")
    public CalcPrecoPrazoWSHttpPost getCalcPrecoPrazoWSHttpPost(WebServiceFeature... features) {
        return super.getPort(CalcPrecoPrazoWSHttpPost, CalcPrecoPrazoWSHttpPost.class, features);
    }

}
